from api.test_model import test_get_model_info_from_api, test_get_model_version_info_from_api
from api.test_creators import test_get_creators_info_simple_from_api
from download.test import test_civitai_download, test_advanced_download

test_get_model_info_from_api()
test_get_model_version_info_from_api()
test_get_creators_info_simple_from_api()
test_civitai_download()
test_advanced_download()