name: Publish Package

on:
  push:
    branches:
      - main

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
          pip install twine
      - name: Install package
        run: |
          pip install -e .
      - name: Build and publish package
        run: |
          python -m build
          python -m twine check dist/*
          python -m twine upload --repository pypi dist/*