name: Upload Python Package

on:
  release:
    types: [published]

permissions:
    contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel build twine
      - name: Build distribution
        run: python -m build
      - name: Upload to PyPI
        run: |
          python -m twine check dist/*
          python -m twine upload dist/*
        env:
          TWINE_USERNAME: ${{secrets.PYPI_USERNAME}}
          TWINE_PASSWORD: ${{secrets.PYPI_API_TOKEN}}