on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel build
      - name: Build distribution
        run: python -m build
      - uses: actions/upload-artifact@v4
        with:
          path: ./dist/*
  test:
    needs: build
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: artifact
          path: dist
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}
      - name: Install dependenies
        run: |
          python -m pip install --upgrade pip
          pip install pytest dist/*.whl
      - name: Test with pytest
        run: |
          pytest tests
      - name: Request Refused(If failure)
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@0.2.0
        with: 
          github-token: ${{github.token}}
          script: |
            const ref = "${{github.ref}}"
            const pull_number = Number(ref.split("/")[2])
            await github.pulls.createReview({
              pull_number,
              event: "REAUEST_CHANGES"
            })
            await github.pulls.update({
              pull_number,
              state: "closed"
            })