on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel build pytest
      - name: Build distribution
        run: python -m build
      - run: |
          pip install dist/*.whl
      - name: Test with pytest
        run: |
          pytest tests
      - name: Request Refused(If failure)
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@0.2.0
        with: 
          github-token: ${{github.token}}
          script: |
            const ref = "${{github.ref}}"
            const pull_number = Number(ref.split("/")[2])
            await github.pulls.createReview({
              pull_number,
              event: "REAUEST_CHANGES"
            })
            await github.pulls.update({
              pull_number,
              state: "closed"
            })